/*
 * ssd1306_tests.c
 *
 *  Created on: Apr 24, 2024
 *      Author: trand
 */


#include <string.h>
#include <stdio.h>
#include "../../Drivers/ssd1306/Inc/ssd1306.h"
#include "../../Drivers/ssd1306/Inc/ssd1306_tests.h"
#include "../../Drivers/ssd1306/Inc/ssd1306_fonts.h"

//------------------------------------------------------------------------------
// Table generated by LCD Assistant
// http://en.radzio.dxp.pl/bitmap_converter/
//------------------------------------------------------------------------------


//const unsigned char icon_reset_16x16[] ={
//		0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x13, 0xc0, 0x14, 0x20, 0x18, 0x10, 0x1e, 0x08, 0x00, 0x08,
//		0x10, 0x08, 0x10, 0x08, 0x08, 0x10, 0x04, 0x20, 0x03, 0xc0, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
//};
//
//// // 'icon_pin_config', 16x16px
// const unsigned char icon_pin_config_16x16[]= {
// 	0x00, 0x00, 0x00, 0x00, 0x3e, 0x00, 0x3e, 0x00, 0x36, 0x00, 0x3e, 0x00, 0x3f, 0x00, 0x03, 0x80,
// 	0x01, 0xc0, 0x00, 0xe0, 0x00, 0x70, 0x74, 0x38, 0x50, 0x18, 0x75, 0xc0, 0x45, 0x40, 0x00, 0x00
// };
//// // 'icon_wifi_access_point', 16x16px
// const unsigned char icon_wifi_access_point_16x16[] = {
// 	0x00, 0x00, 0x01, 0xe0, 0x00, 0x10, 0x00, 0x08, 0x00, 0xc4, 0x08, 0x22, 0x0c, 0x12, 0x0e, 0x92,
// 	0x07, 0x02, 0x03, 0x80, 0x05, 0xc0, 0x04, 0xe0, 0x0e, 0x00, 0x0e, 0x00, 0x1f, 0x00, 0x00, 0x00
// };



//void ssd1306_TestBorder() {
//    ssd1306_Fill(Black);
//
//    uint8_t x = 0;
//    uint8_t y = 0;
//    do {
//        ssd1306_DrawPixel(x, y, Black);
//
//        if((y == 0) && (x < (SSD1306_WIDTH-1)))
//            x++;
//        else if((x == (SSD1306_WIDTH-1)) && (y < (SSD1306_HEIGHT-1)))
//            y++;
//        else if((y == (SSD1306_HEIGHT-1)) && (x > 0))
//            x--;
//        else
//            y--;
//
//        ssd1306_DrawPixel(x, y, White);
//        ssd1306_UpdateScreen();
//
//        HAL_Delay(5);
//    } while(x > 0 || y > 0);
//
//    HAL_Delay(1000);
//}
//
//void ssd1306_TestFonts1() {
//    uint8_t y = 0;
//    ssd1306_Fill(Black);
//
//    #ifdef SSD1306_INCLUDE_FONT_16x26
//    ssd1306_SetCursor(2, y);
//    ssd1306_WriteString("Font 16x26", Font_16x26, White);
//    y += 26;
//    #endif
//
//    #ifdef SSD1306_INCLUDE_FONT_11x18
//    ssd1306_SetCursor(2, y);
//    ssd1306_WriteString("Font 11x18", Font_11x18, White);
//    y += 18;
//    #endif
//
//    #ifdef SSD1306_INCLUDE_FONT_7x10
//    ssd1306_SetCursor(2, y);
//    ssd1306_WriteString("Font 7x10", Font_7x10, White);
//    y += 10;
//    #endif
//
//    #ifdef SSD1306_INCLUDE_FONT_6x8
//    ssd1306_SetCursor(2, y);
//    ssd1306_WriteString("Font 6x8", Font_6x8, White);
//    #endif
//
//    ssd1306_UpdateScreen();
//}
//
///*
// * This test shows how an 128x64 px OLED can replace a 0802 LCD.
// */
//void ssd1306_TestFonts2() {
//#ifdef SSD1306_INCLUDE_FONT_16x24
//    uint8_t x1, y1, x2, y2;
//
//    ssd1306_Fill(Black);
//
//    ssd1306_SetCursor(0, 4);
//    ssd1306_WriteString("18.092.5", Font_16x24, White);
//    ssd1306_SetCursor(0, 4+24+8);
//    ssd1306_WriteString("RIT+1000", Font_16x24, White);
//
//    // underline
//    x1 = 6*16;
//    y1 = 4+24+8+24;
//    x2 = x1+16;
//    y2 = y1+2;
//    ssd1306_FillRectangle(x1, y1, x2, y2, White);
//
//    ssd1306_UpdateScreen();
//#endif
//}
//
///*
// * Test of proportional (non-monospaced) font.
// */
//void ssd1306_TestFonts3() {
//    ssd1306_Fill(Black);
//#ifdef SSD1306_INCLUDE_FONT_16x15
//    ssd1306_SetCursor(4, 4);
//    ssd1306_WriteString("Proportional", Font_16x15, White);
//    ssd1306_SetCursor(4, 24);
//    ssd1306_WriteString("text... Sweet!", Font_16x15, White);
//    ssd1306_SetCursor(4, 44);
//    ssd1306_WriteString("3.1415  04:20", Font_16x15, White);
//#elif defined(SSD1306_INCLUDE_FONT_11x18)
//    ssd1306_SetCursor(4, 4);
//    ssd1306_WriteString("Skip test", Font_11x18, White);
//    ssd1306_SetCursor(4, 24);
//    ssd1306_WriteString("Font not", Font_11x18, White);
//    ssd1306_SetCursor(4, 44);
//    ssd1306_WriteString("included!", Font_11x18, White);
//#endif
//    ssd1306_UpdateScreen();
//}

//void ssd1306_InitializeDevice(){
//	ssd1306_Init();
//
//
//	uint32_t start = HAL_GetTick();
//	uint32_t end = start;
//	int fps = 0;
//	char message[] = "*** TESTING FPS ***";
//
//
//	ssd1306_Fill(Black);
//	ssd1306_SetCursor(2,0);
//	ssd1306_WriteString("Hello...", Font_6x8, White);
//	ssd1306_SetCursor(2,12);
//	ssd1306_WriteString("Initilized Device", Font_6x8, White);
//	ssd1306_UpdateScreen();
//
//	do {
//		ssd1306_SetCursor(2, 25);
//		ssd1306_WriteString(message, Font_11x18, Black);
//		ssd1306_UpdateScreen();
//
//		char ch = message[0];
//		memmove(message, message+1, sizeof(message)-2);
//		message[sizeof(message)-2] = ch;
//		fps++;
//	    end = HAL_GetTick();
//	} while((end - start) < 5000);
//
//	 char buff[64];
//	 fps = (float)fps / ((end - start) / 1000.0);
//	 snprintf(buff, sizeof(buff), "~%d FPS", fps);
//	 ssd1306_SetCursor(2, 45);
//	 ssd1306_WriteString(buff, Font_11x18, White);
//	 ssd1306_UpdateScreen();
//
//	 HAL_Delay(2000);
//	 /*---WELCOME PART---*/
//	 ssd1306_Fill(Black);
//	 ssd1306_SetCursor(30,0);
//	 ssd1306_WriteString("WELCOME", Font_11x18, White);
//	 ssd1306_SetCursor(50,20);
//	 ssd1306_WriteString("Noise", Font_7x10, White);
//	 ssd1306_SetCursor(5,30);
//     ssd1306_WriteString("Measure & Warning", Font_7x10, White);
//     ssd1306_SetCursor(45,40);
//     ssd1306_WriteString("Device", Font_7x10, White);
//	 ssd1306_UpdateScreen();
//
//}

void ssd1306_InitializeDevice(){
	ssd1306_Init();
	ssd1306_Fill(Black);
	ssd1306_SetCursor(2,2);
	ssd1306_WriteString("Loading...", Font_7x10, White);
	ssd1306_SetCursor(2,14);
	ssd1306_WriteString("Initilized Device", Font_7x10, White);
	ssd1306_UpdateScreen();

	// Simulate loading process
	for (uint8_t i = 0; i <= 100; i++) {
	        showProgress(i);
	        HAL_Delay(100);
	}
	HAL_Delay(1000);
}

void showProgress(uint8_t progress)
{
    uint8_t barWidth = 100;  // Width of the progress bar
    uint8_t barHeight = 10;  // Height of the progress bar
    uint8_t x = (128 - barWidth) / 2;  // Center horizontally
    uint8_t y = 32;  // Center vertically


    // Draw the progress bar border
    ssd1306_DrawRectangle(x, y, x + barWidth, y + barHeight, White);

    // Calculate the width of the filled part of the progress bar
    uint8_t fillWidth = (progress * barWidth) / 100;

    // Draw the filled part of the progress bar
    ssd1306_FillRectangle(x, y, x + fillWidth, y + barHeight, White);

    // Update the display
    ssd1306_UpdateScreen();
}

void test(char* value1,char* noti){
	ssd1306_Fill(Black);

	ssd1306_SetCursor(5,6);
	ssd1306_WriteString("Set Up Wifi", Font_11x18, White);

	ssd1306_SetCursor(5,35);
	ssd1306_WriteString(noti, Font_7x10, White);


	ssd1306_SetCursor(5,50);
    ssd1306_WriteString(value1, Font_7x10, White);



	ssd1306_UpdateScreen();
}

void showMonitoring(char* value){
	char buffer[10]={0};
	ssd1306_Fill(Black);


	strcat(buffer,value);
	strcat(buffer," dB");

	ssd1306_SetCursor(20,35);
	ssd1306_WriteString(buffer, Font_11x18, White);

    ssd1306_UpdateScreen();
}


//
//void ssd1306_TestFPS() {
//
//    ssd1306_Fill(Black);
//
//    uint32_t start = HAL_GetTick();
//    uint32_t end = start;
//    int fps = 0;
//    char message[] = "ABCDEFGHIJK";
//
//    ssd1306_SetCursor(0,0);
//    ssd1306_WriteString("Initializing...", Font_11x18, White);
//
//    do {
//        ssd1306_SetCursor(2, 18);
//        ssd1306_WriteString(message, Font_11x18, Black);
//        ssd1306_UpdateScreen();
//
//        char ch = message[0];
//        memmove(message, message+1, sizeof(message)-2);
//        message[sizeof(message)-2] = ch;
//
//        fps++;
//        end = HAL_GetTick();
//    } while((end - start) < 5000);
//
//    HAL_Delay(5000);
//
//    char buff[64];
//    fps = (float)fps / ((end - start) / 1000.0);
//    snprintf(buff, sizeof(buff), "~%d FPS", fps);
//
//    ssd1306_Fill(White);
//    ssd1306_SetCursor(2, 2);
//    ssd1306_WriteString(buff, Font_11x18, Black);
//
//    ssd1306_UpdateScreen();
//}

//void ssd1306_TestLine() {
//
//  ssd1306_Line(1,1,SSD1306_WIDTH - 1,SSD1306_HEIGHT - 1,White);
//  ssd1306_Line(SSD1306_WIDTH - 1,1,1,SSD1306_HEIGHT - 1,White);
//  ssd1306_UpdateScreen();
//  return;
//}
//
//void ssd1306_TestRectangle() {
//  uint32_t delta;
//
//  for(delta = 0; delta < 5; delta ++) {
//    ssd1306_DrawRectangle(1 + (5*delta),1 + (5*delta) ,SSD1306_WIDTH-1 - (5*delta),SSD1306_HEIGHT-1 - (5*delta),White);
//  }
//  ssd1306_UpdateScreen();
//  return;
//}
//
//void ssd1306_TestRectangleFill() {
//  ssd1306_FillRectangle(31, 1, 65, 35, White);
//  ssd1306_FillRectangle(10, 45, 70, 60, White);
//  ssd1306_FillRectangle(75, 10, 100, 45, White);
//  ssd1306_FillRectangle(55, 30, 80, 55, Black);
//  ssd1306_UpdateScreen();
//}
//
//void ssd1306_TestRectangleInvert() {
//#ifdef SSD1306_INCLUDE_FONT_11x18
//  ssd1306_SetCursor(2, 0);
//  ssd1306_WriteString("Black", Font_11x18, White);
//  ssd1306_SetCursor(2, 20);
//  ssd1306_WriteString("on", Font_11x18, White);
//  ssd1306_SetCursor(2, 40);
//  ssd1306_WriteString("White", Font_11x18, White);
//  ssd1306_SetCursor(66, 0);
//  ssd1306_WriteString("White", Font_11x18, White);
//  ssd1306_SetCursor(66, 20);
//  ssd1306_WriteString("on", Font_11x18, White);
//  ssd1306_SetCursor(66, 40);
//  ssd1306_WriteString("Black", Font_11x18, White);
//#else
//  ssd1306_FillCircle(32, 32, 20, White);
//  ssd1306_FillCircle(96, 32, 20, White);
//#endif
//  ssd1306_InvertRectangle(0,0,63,63);
//  /* Test rectangle lies on one 8px page */
//  ssd1306_InvertRectangle(2,58,125,60);
//  ssd1306_UpdateScreen();
//}
//
//void ssd1306_TestCircle() {
//  uint32_t delta;
//
//  for(delta = 0; delta < 5; delta ++) {
//    ssd1306_DrawCircle(20*delta+30, 15, 10, White);
//  }
//
//  for(delta = 0; delta < 5; delta ++) {
//    ssd1306_FillCircle(23*delta+15, 40, 10, White);
//  }
//
//  ssd1306_UpdateScreen();
//  return;
//}
//
//void ssd1306_TestArc() {
//  ssd1306_DrawArc(30, 30, 30, 20, 270, White);
//  ssd1306_DrawArcWithRadiusLine(80, 55, 10, 30, 270, White);
//  ssd1306_UpdateScreen();
//  return;
//}
//
//void ssd1306_TestPolyline() {
//  SSD1306_VERTEX loc_vertex[] =
//  {
//      {35,40},
//      {40,20},
//      {45,28},
//      {50,10},
//      {45,16},
//      {50,10},
//      {53,16}
//  };
//
//  ssd1306_Polyline(loc_vertex,sizeof(loc_vertex)/sizeof(loc_vertex[0]),White);
//  ssd1306_UpdateScreen();
//  return;
//}
//
//void ssd1306_TestDrawBitmap()
//{
//	  ssd1306_Fill(Black);
//
//	  ssd1306_DrawBitmap(8, 2, icon_pin_config_16x16,16,16, White);
//	  ssd1306_DrawBitmap(8, 24, icon_wifi_access_point_16x16,16,16, White);
//	  ssd1306_DrawBitmap(8, 46, icon_reset_16x16,16,16, White);
//
//	  ssd1306_SetCursor(28,8);
//	  ssd1306_WriteString("Pin Config", Font_7x10, White);
//
//	  ssd1306_SetCursor(28,28);
//	  ssd1306_WriteString("Wifi AP", Font_7x10, White);
//
//	  ssd1306_SetCursor(28,50);
//	  ssd1306_WriteString("Reset", Font_7x10, White);
//
//	  ssd1306_UpdateScreen();
//}
//
//
//void ssd1306_TestAll() {
//
// //   ssd1306_Init();
//
////    ssd1306_TestFPS();
////    HAL_Delay(3000);
////
////    ssd1306_TestDrawBitmap();
////    HAL_Delay(3000);
//
//
////    ssd1306_TestBorder();
////    ssd1306_TestFonts1();
////    HAL_Delay(3000);
////    ssd1306_TestFonts2();
////    HAL_Delay(3000);
////    ssd1306_TestFonts3();
////    HAL_Delay(3000);
////    ssd1306_Fill(Black);
////    ssd1306_TestRectangle();
////    ssd1306_TestLine();
////    HAL_Delay(3000);
////    ssd1306_Fill(Black);
////    ssd1306_TestRectangleFill();
////    HAL_Delay(3000);
////    ssd1306_Fill(Black);
////    ssd1306_TestRectangleInvert();
////    HAL_Delay(3000);
////    ssd1306_Fill(Black);
////    ssd1306_TestPolyline();
////    HAL_Delay(3000);
////    ssd1306_Fill(Black);
////    ssd1306_TestArc();
////    HAL_Delay(3000);
////    ssd1306_Fill(Black);
////    ssd1306_TestCircle();
////    HAL_Delay(3000);
//
//}
